# Generated by Django 5.2.6 on 2026-02-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_declutteritem_category_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='declutteritem',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
