# Generated by Django 5.2.6 on 2026-02-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_declutteritem_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='lock_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='lock_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
