# Generated by Django 5.2.6 on 2026-02-15 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_failed_attempts_user_lock_level_user_lock_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
